### PR TITLE
Optimize README load time.

### PR DESCRIPTION
**Pull request by jchristgit**
Valued friend Joe,

I have inlined the profile badges in order to optimize loading time.
A new `Makefile` is added. Running `make` will update the images.
Users visiting your profile will experience a better page load time, as
the content is served from GitHub directly, and thus does not need to
open more HTTPS connections.

The `make` command should be run in a cronjob with daily updates pushed
to this repository. This is out of scope for this commit.

Thank you,
Johannes

### CODE REVIEW

**Comment by jchristgit** [comment]
Valued friend Joe,

to save more space, a possible future feature may be compressing the SVG files.
This is out of scope for this commit.

Thank you,
Johannes

**Review by 0xAda — APPROVED** [review]

**Review by jerbob — APPROVED** [review]

**Review by thebeanogamer — APPROVED** [review]

**Comment by jerbob** [comment]
Good evening @jb3,

Do you have an ETA (Estimated Time of Approval) for this Pull Request?

Looking forward to hearing from you,
Boby

**Comment by jb3** [comment]
Hello, whilst the contribution is appreciated. The static assets in question are already served by the GitHub CDN servers, they are not served from the URLs directly mentioned in the markdown file, they are instead proxied (example: https://camo.githubusercontent.com/60370af77f088382336a42e10798b1cb26b876e71b3ea36e10112b4eeb1763a7/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d6a623326636f756e745f707269766174653d74727565266c696e655f6865696768743d32312673686f775f69636f6e733d7472756526686964655f626f726465723d74727565267468656d653d64726163756c61)

I have locked this PR due to the above spam, I hope that you understand. Again, thank you for the contribution.

**Comment by jchristgit** [comment]
Valued friend Joe,

Thank you for clarifying on the purpose of GitHub's `camo` subdomain and
caching the results of the SVG loads for user requests to not be intercepted.

It appears that you have misunderstood my original pull request: I am aware of
the dynamic content sitting behind the SVG files, but I believe that by
inlining the remote fetch to the `camo` subdomain, we can improve it
regardless, as you essentially move the processing required into a crontab on
your machine.

In case you were wondering, `crontab` and `crond` is a system for managing
scheduled jobs on unix-like systems, including your laptop. There are also
alternatives such as `anacron` which may prove useful.

Again, Joe, thank you for the explanation. It is highly appreciated. I do
believe we can stay friends despite our differences.

Thank you,
Johannes

**Pull request closed without merging**
